# Generated by Django 2.1.5 on 2019-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('house_num', models.IntegerField()),
            ],
        ),
    ]
